# Generated by Django 6.0.2 on 2026-02-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=100)),
                ('requester_contact', models.CharField(max_length=10)),
                ('device_name', models.CharField(max_length=50)),
                ('device_type', models.CharField(choices=[('aio', 'AIO'), ('laptop', 'Laptop'), ('system unit', 'System Unit'), ('monitor', 'Monitor'), ('other', 'Other')], default='system unit', max_length=20)),
                ('problem_type', models.CharField(choices=[('network', 'Network'), ('software', 'Software'), ('hardware', 'Hardware'), ('other', 'Other')], default='software', max_length=10)),
                ('problem_desc', models.TextField(blank=True, null=True)),
                ('district', models.CharField(choices=[('adenta', 'Adenta'), ('legon', 'Legon'), ('teshie', 'Teshie'), ('makola', 'Makola'), ('roman ridge', 'Roman Ridge'), ('dodowa', 'Dodowa'), ('mampong', 'Mampong'), ('kwabenya', 'Kwabenya'), ('regional office', 'Regional office')], default='regional office', max_length=20)),
                ('room_number', models.CharField(blank=True, max_length=3, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('received_by', models.CharField(max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
